apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment  # Ensure this matches your Deployment metadata name
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource  # Using Resource to scale based on CPU or memory (for example)
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Target CPU utilization to 70%