apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kyueran/cs3219-frontend:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RUNTIME_FRONTEND_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: FRONTEND_SERVICE
            - name: RUNTIME_QUESTION_PATH
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: QUESTION_PATH
            - name: RUNTIME_USER_PATH
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: USER_PATH
            - name: RUNTIME_MATCHING_PATH
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: MATCHING_PATH
            - name: RUNTIME_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_URL
            - name: RUNTIME_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_ANON_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
