apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: thesoggy/peerprep-matching-service:kub
          imagePullPolicy: Always
          ports:
            - containerPort: 6006
          env:
            - name: MATCHING_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: MATCHING_SERVICE_PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: NODE_ENV
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service-service
spec:
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 6006
      targetPort: 6006
