apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0
        args: ["--appendonly", "yes", "--requirepass", "$(REDIS_PASSWORD)"]
        envFrom:
        - configMapRef:
            name: judge0-db-config
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "250m" # This is the amount of CPU the application requests
          limits:
            cpu: "750m" # This is the maximum amount of CPU the application can use
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
