apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-server
  template:
    metadata:
      labels:
        app: judge0-server
    spec:
      containers:
      - name: server
        image: judge0/judge0:1.13.0
        ports:
        - containerPort: 2358
        resources:
          requests:
            cpu: "250m" # This is the amount of CPU the application requests
          limits:
            cpu: "750m" # This is the maximum amount of CPU the application can use
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: judge0-db-config
---
apiVersion: v1
kind: Service
metadata:
  name: judge0-server-service
spec:
  selector:
    app: judge0-server
  ports:
  - protocol: TCP
    port: 2358
    targetPort: 2358

